
spring:

  cloud:

    gateway:
      routes:
        - id: ms2
          uri: lb://MS2
          predicates:
            - Path=/ms2/**
            
        # - id: websocket_route2
        #   uri: lb:ws://WEBSOCKET-SERVICE
        #   predicates:
        #     - Path=/websocket/** # ws://localhost:80/websocket/hi
