server:
  port: 0

spring:

  
  rabbitmq: # RabbitMQ 관련 설정
    host: localhost
    port: 5672
    username: ssafy
    password: ssafy
      
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh, refresh

msg:
  name: hi, taehun. it's good night time!!
